---
  name: ci

  on:
    pull_request:
    push:
      branches:
        - master

  jobs:
    delivery:
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@master
        # - name: Run Chef Delivery
        # #   uses: actionshub/chef-delivery@master
        #   env:
        #     CHEF_LICENSE: accept-no-persist

    # dokken:
    #   needs: [delivery]
    #   runs-on: ubuntu-latest
    #   strategy:
    #     matrix:
    #       os:
    #         - 'amazonlinux'
    #         - 'amazonlinux-2'
    #         - 'debian-9'
    #         - 'debian-10'
    #         - 'centos-6'
    #         - 'centos-7'
    #         - 'centos-8'
    #         - 'oraclelinux-6'
    #         - 'oraclelinux-7'
    #         # - 'oraclelinux-8'
    #         - 'fedora-latest'
    #         - 'ubuntu-1604'
    #         - 'ubuntu-1804'
    #         - 'opensuse-leap-15'

    #       suite:
    #         - 'package'
    #         - 'service'
    #         - 'service-auth'
    #         - 'sup'
    #         - 'config'
    #         - 'config-auth'
    #         - 'user-toml'
    #         - 'license'
    #         - 'config-chef-13'
    #         - 'config-chef-13-auth'
    #     fail-fast: false

    #   steps:
    #     - name: Check out code
    #       uses: actions/checkout@master
    #     - name: Install Chef
    #       uses: actionshub/chef-install@master
    #     - name: Dokken
    #       uses: actionshub/kitchen-dokken@master
    #       env:
    #         CHEF_LICENSE: accept-no-persist
    #         KITCHEN_LOCAL_YAML: kitchen.dokken.yml
    #       with:
    #         suite: ${{ matrix.suite }}
    #         os: ${{ matrix.os }}

    windows:
      needs: [delivery]
      runs-on: windows-2019
      strategy:
        matrix:
          os:
            - 'windows-2019'
          suite:
            - 'win-config'
            # - 'win_license'
            # - 'win_package'
            # - 'win_service'
            # - 'win_sup'
            # - 'win_user_toml'
        fail-fast: false
      steps:
        - name: Check out code
          uses: actions/checkout@master
        - name: Install Chef
          uses: sam1el/chef-install@add-to-path
        # - name: Testing stuff
        #   run: gci $ENV:TEMP
        #   shell: powershell
        # - name: Testing stuff
        #   run:  New-Item "$env:temp\kitchen" -ItemType directory
        #   shell: powershell
        - name: Test Kitchen
          uses: sam1el/test-kitchen@windows_commands
          env:
            CHEF_LICENSE: accept-no-persist
            KITCHEN_LOCAL_YAML: kitchen.windows.yml
          with:
            suite: ${{ matrix.suite }}
            os: ${{ matrix.os }}
        - name: Catting the log file
          run:  Get-Content ".kitchen/logs/kitchen.log" | out-String | Write-Output
          shell: powershell
          if: always()
        - name: Test Kitchen
          uses: sam1el/test-kitchen@windows_commands
          env:
            CHEF_LICENSE: accept-no-persist
            KITCHEN_LOCAL_YAML: kitchen.windows.yml
          with:
            suite: ${{ matrix.suite }}
            os: ${{ matrix.os }}
            action: diagnose
          if: always()
        # - name: Add Chef Workstation to PATH
        #   run: echo "##[add-path]C:\opscode\chef-workstation\bin\;"
        #   shell: powershell
        # - name: Chef Infra Client Run
        #   run: chef-solo -c test/solo.rb -o "test::${{ matrix.suite }}"
        #   shell: powershell
        #   env:
        #     CHEF_LICENSE: accept-no-persist
        # - name: Integration Testing
        #   run: inspec exec test\integration\${{ matrix.suite }}\default_spec.rb
        #   shell: powershell
        #   env:
        #     CHEF_LICENSE: accept-no-persist
